services:
  backend:
    build: ./backend
    ports:
      - "8082:3000"
    env_file: /home/dev/secrets/echo-back.env
  frontend:
    build: ./frontend
    ports:
      - "8083:3001"
    env_file: /home/dev/secrets/echo-front.env