### Variables
@baseUrl = http://localhost:3000
@token = 'eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zMmVTeTlyZ1p5U3l3NElERWVPa0Zsandnb2siLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6ImFzaWF0aXR1ZGU1NTRAZ21haWwuY29tIiwiZXhwIjoxNzYxMjQwMTQyLCJpYXQiOjE3NjEyMzY1NDIsImlkIjoidXNlcl8zNFRRQ2E5WThDRjJ1RnQ1RFVqdzRUSDdmVDgiLCJpc3MiOiJodHRwczovL25vdGFibGUtc3VuZmlzaC01My5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI4MTQ5NGE3ZmEwYWY4ZDU1ZjRjNCIsIm5iZiI6MTc2MTIzNjUzNywic3ViIjoidXNlcl8zNFRRQ2E5WThDRjJ1RnQ1RFVqdzRUSDdmVDgiLCJ1c2VybmFtZSI6ImFzaWEifQ.h9D8gitlkpXCs-1MbbQ4ORQ6O1dsmU52v21namSLZq77tDGDcgI7_pnW3RobBxShMYpn33WaywVasZBvanIRIZ3oMpsO-OqSZUVzEAivoOkXv3ON8HqpqjBUIjWkbzopHJ-vRzX3FVgegTJErpBb_lGO-5cmnaqL22ifacXNR73JOAdIxmiiveOFEjEo_iw3oJDHDcEx-VJr18meMmspzlErEi20T1Tuch7n8eRIgWzr8GXb6RUFQj9_D55mG9jEoEbebG5HhWVuyERw2Xgc9Qw9OZA0fhU5bgl47dnxWVi8bw5BPytLc4cFMf_woe99Lxg7ploG_uAFvYreGliDjQ'

### Test Health Check
GET http://localhost:3000/api/health
Accept: application/json


### Get All Conversations (authentifié)
GET {{baseUrl}}/conversations
Authorization: Bearer {{token}}

### Create Conversation
POST {{baseUrl}}/conversations
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "First chat"
}

### Send Message
POST {{baseUrl}}/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Hello World!",
  "conversationId": "b522f6ec-3e3d-4844-8d47-112754bf822e"
}

### Get Messages
GET {{baseUrl}}/messages?conversationId=b522f6ec-3e3d-4844-8d47-112754bf822e
Authorization: Bearer {{token}}
